import Head from "next/head";

import LandingPage from "../components/landingPage";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Desa Wisata Nglanggeran</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Logo_GAP.ico" />
      </Head>

      <main className={styles.main}>
        <LandingPage />
      </main>
    </div>
  );
}
